RDKCOM-3250: REFPLTB-1779 RPi Build failure in Utopia
This change introduced build failures in Utopia on RPi platforms:
https://code.rdkcentral.com/r/c/rdkb/components/opensource/ccsp/Utopia/+/73844
Error:
| Utopia/source/scripts/init/c_registration/02_bridge.c:65:55: error: 'SERVICE_CUSTOM_EVENTS' undeclared (first use in this function)
|    65 |    sm_register(SERVICE_NAME, SERVICE_DEFAULT_HANDLER, SERVICE_CUSTOM_EVENTS);
|       |                                                       ^~~~~~~~~~~~~~~~~~~~~
| Utopia/source/scripts/init/c_registration/02_bridge.c:65:55: note: each undeclared identifier is reported only once for each function it appears in

Reason for change: REFPLTB-1779 RPi Build failure in Utopia
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen_barrett@comcast.com>

(cherry picked from commit 78ef20df22f983e9f5fd3e7a61a0059d97d0dd81)
Change-Id: I719281db40f74ad2f3e937d75b5b5cc307d6112d