RDKCOM-273:raw_socket_send.c:include<netinet/if_ether.h>bfore<linux/if_ether.h>
Musl and the kernel uapi headers will align on a fix for this
eventually, but for now the order of including <netinet/if_ether.h>
and <linux/if_ether.h> matters when building with musl libc.
 | In file included from /.../tmp/sysroots/raspberrypi-rdk-broadband-musl/usr/i
nclude/netinet/ether.h:8:0,
 |                  from ../../../git/source/firewall/raw_socket_send.c:54:
 | /.../tmp/sysroots/raspberrypi-rdk-broadband-musl/usr/include/netinet/if_ethe
r.h:101:8: error: redefinition of 'struct ethhdr'
 |  struct ethhdr {
 |         ^~~~~~
 | In file included from ../../../git/source/firewall/raw_socket_send.c:41:0:
 | /.../tmp/sysroots/raspberrypi-rdk-broadband-musl/usr/include/linux/if_ether.
h:143:8: note: originally defined here
 |  struct ethhdr {
 |         ^~~~~~
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Reason for change: raw_socket_send.c: include <netinet/if_ether.h> before <linu
x/if_ether.h>
Test Procedure: None.
Risks: Low.

(cherry picked from commit ad81bc065f5ad929775574671fdc867955d7bfdb)
(cherry picked from commit 1a65b5114e7ea0ca97396267a6908087fb703f09)

Change-Id: I7a98575234bd8d0c8e0b66f1180b5960af7ba72a