REFPLTB-1779 RPi Build failure in Utopia
This change introduced build failures in Utopia on RPi platforms:
https://code.rdkcentral.com/r/c/rdkb/components/opensource/ccsp/Utopia/+/73844
Error:
| Utopia/source/scripts/init/c_registration/02_bridge.c:65:55: error: 'SERVICE_CUSTOM_EVENTS' undeclared (first use in this function)
|    65 |    sm_register(SERVICE_NAME, SERVICE_DEFAULT_HANDLER, SERVICE_CUSTOM_EVENTS);
|       |                                                       ^~~~~~~~~~~~~~~~~~~~~
| Utopia/source/scripts/init/c_registration/02_bridge.c:65:55: note: each undeclared identifier is reported only once for each function it appears in

Change-Id: Ib716d330cc096ed57600786affdef81753b3e744