RDKCOM-3435: RDKBCMF-296 Utopia build failure in RPi4 Broadband 64bit
Reason for change: build errors in utopia while building RPi4 Broadband 64bit:
| Utopia/source/service_dhcp/service_dhcp_server.c:221:58: error: format '%d' expects argument of type 'int', but argument 5 has type 'long unsigned int' [-Werror=format=]
|   221 |             fprintf(stdout, DNSMASQ getRFC_Value %s %s %d\n,status,l_DnsStrictOrderStatus,sizeof(l_DnsStrictOrderStatus));
|       |                                                         ~^                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                          |                                  |
|       |                                                          int                                long unsigned int
|       |                                                         %ld
| Utopia/source/service_dhcp/service_dhcp_server.c:225:78: error: format '%d' expects argument of type 'int', but argument 5 has type 'long unsigned int' [-Werror=format=]
|   225 |             fprintf(stdout, FAILURE: DNSMASQ getRFC_Value syscfg_get %s %s %d\n,status,l_DnsStrictOrderStatus,sizeof(l_DnsStrictOrderStatus));
|       |                                                                             ~^                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                                              |                                  |
|       |                                                                              int                                long unsigned int
|       |                                                                             %ld

Test Procedure: Broadband 64bit build OK

Risks: None.

Signed-off-by: Simon Chung <simon_chung@comcast.com>
(cherry picked from commit 05cabcdf9d9c90ac33164e075d4058b6fb032bc5)
Change-Id: I602786a2687b94b2c2d2ab59f55aa8067fab948b