RDKCOM-353: utopia_init_xb6.sh: remove unnecessary 's' suffix from sleep command
Adding an 's' suffix to sleep command arguments is non-portable and
unnecessary.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Reason for change: utopia_init_xb6.sh: remove unnecessary 's' suffix from sleep command
Test Procedure: None.
Risks: Low.

(cherry picked from commit b70dadfcee5a775fc87bfff648b66b5078bd7b9f)

RDKCOM-354: gcc 7 build fixes

 | /usr/src/debug/utopia/2.1+gitAUTOINC+_9421836757-r0/git/source/firewall/firewall.c:1400: error: undefined reference to 'SET_IPT_PRI_DEFAULT'
 | /usr/src/debug/utopia/2.1+gitAUTOINC+_9421836757-r0/git/source/firewall/firewall.c:1403: error: undefined reference to 'SET_IPT_PRI_MODULD'
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Reason for change: gcc 7 build fixes
Test Procedure: None.
Risks: Low.

(cherry picked from commit c1a6b17ca42e72bc54241329a5d3989295b7ad2c)
(cherry picked from commit 2757c40e693e58b307343a2751d30fb9bd450dc9)

Change-Id: I1881a9e18ebebeea491ab801c772cc7ccb51060c