RDKBCMF-296 Utopia build failure in RPi4 Broadband 64bit
build errors in utopia while building RPi4 Broadband 64bit:
| Utopia/source/service_dhcp/service_dhcp_server.c:221:58: error: format '%d' expects argument of type 'int', but argument 5 has type 'long unsigned int' [-Werror=format=]
|   221 |             fprintf(stdout, DNSMASQ getRFC_Value %s %s %d\n,status,l_DnsStrictOrderStatus,sizeof(l_DnsStrictOrderStatus));
|       |                                                         ~^                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                          |                                  |
|       |                                                          int                                long unsigned int
|       |                                                         %ld
| Utopia/source/service_dhcp/service_dhcp_server.c:225:78: error: format '%d' expects argument of type 'int', but argument 5 has type 'long unsigned int' [-Werror=format=]
|   225 |             fprintf(stdout, FAILURE: DNSMASQ getRFC_Value syscfg_get %s %s %d\n,status,l_DnsStrictOrderStatus,sizeof(l_DnsStrictOrderStatus));
|       |                                                                             ~^                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                                              |                                  |
|       |                                                                              int                                long unsigned int
|       |                                                                             %ld

Change-Id: Idbfb70cbe7dbe8a794a794c7dc7a92ca86b8659a
(cherry picked from commit 29db4cfc04634d3020b5e5ccfd2f7f050e8c8e88)